name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build production image
    runs-on: [self-hosted, home]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: frankenphp_prod
          push: false
          tags: kivvi-click:ci
